baseurl = "http://ryanmccarl.com/"
title = "Ryan McCarl"
subtitle = "Attorney | Writer | Educator"
theme = "academic"
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-38165959-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Ryan McCarl"
  role = "Attorney | Writer | Educator"
  organization = "Founder, WordBrewery"
  organization_url = "https://wordbrewery.com"
  avatar = "ryanmccarlheadshotsmall.jpg"
  email = "admin@wordbrewery.com"

  # Enable Keybase in Contact section by entering your keybase.io username.
  #keybase = "ryanmccarl"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2 Jan 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  highlight_languages = ["go", "lisp", "python", "js", "bash", "CSS", "markdown", "HTML", "XML"]
  #
  #   highlight_style

#     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ['custom.css']
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "https://facebook.com/rmccarl"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/RyanMcCarl"

  [[params.social]]
    icon = "quora"
    icon_pack = "fa"
    link = "https://www.quora.com/profile/Ryan-McCarl"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/ryanmccarl/"

  # [[params.social]]
  #  icon = "google-plus"
  #  icon_pack = "fa"
  #  link = "https://plus.google.com/+ryanmccarl"

  # [[params.social]]
  #  icon = "tumblr"
  #  icon_pack = "fa"
  #  link = "https://wordbrewery.tumblr.com"

  [[params.social]]
    icon = "youtube"
    icon_pack = "fa"
    link = "https://youtube.com/wordbrewerylanguages"

  # [[params.social]]
  #  icon = "pinterest"
  #  icon_pack = "fa"
  #  link = "https://www.pinterest.com/ryanmccarl/"

  # [[params.social]]
  #   icon = "book"
  #   icon_pack = "fa"
  #   link = "https://ssrn.com/author=1405802"

  # [[params.social]]
  #   icon = "medium"
  #   icon_pack = "fa"
  #   link = "https://medium.com/@ryanmccarl"

  # [[params.social]]
  #   icon = "reddit"
  #   icon_pack = "fa"
  #   link = "https://www.reddit.com/user/rmccarl/"

  # [[params.social]]
  #   icon = "github"
  #   icon_pack = "fa"
  #   link = "https://github.com/ryanmccarl"

  # [[params.social]]
  #   icon = "envelope"
  #   icon_pack = "fa"
  #   link = "mailto:admin@wordbrewery.com"

  # [[params.social]]
  #   icon = "angellist"
  #   icon_pack = "fa"
  #   link = "https://angel.co/wordbrewery"

  # [[params.social]]
  #   icon = "google-scholar"
  #   icon_pack = "ai"
  #   link = "https://scholar.google.com/citations?hl=en&user=UOvM2ycAAAAJ"

  # [[params.social]]
  #   icon = "stumbleupon"
  #   icon_pack = "fa"
  #   link = "https://www.stumbleupon.com/stumbler/ryanmccarl"

  # [[params.social]]
  #   icon = "stackexchange"
  #   icon_pack = "fa"
  #   link = "https://stackexchange.com/users/6578807/wordbrewery"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 2

#[[menu.main]]
#  name = "Writing"
#  url = "#publications_selected"
#  weight = 3

[[menu.main]]
  name = "WordBrewery"
  url = "https://wordbrewery.com"
  weight = 4

[[menu.main]]
  name = "Wide Awake Minds"
  url = "http://www.wideawakeminds.com"
  weight = 5

[[menu.main]]
  name = "SSRN"
  url = "https://ssrn.com/author=1405802"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 10

# [[menu.main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 4

# [[menu.main]]
#   name = "Teaching"
#   url = "#teaching"
#   weight = 5

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
